- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azurearm'
    subscriptionId: 'd1a072bc-69ca-42c9-b02c-648ba7862db2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'apj'
    location: 'Brazil US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://djastoragej123jay.blob.core.windows.net/templates/storage.json'
    csmParametersFileLink: 'https://djastoragej123jay.blob.core.windows.net/templates/storage.parameters.json'
    deploymentMode: 'Incremental'