trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azurearm'
    subscriptionId: 'd1a072bc-69ca-42c9-b02c-648ba7862db2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'apj'
    location: 'Brazil US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://dev.azure.com/darshanaj/_git/armtemplate?path=/vm.json'
    csmParametersFileLink: 
    deploymentMode: 'Incremental'